---
- name: Setup for Debian and Ubuntu
  import_tasks: apt.yml
  when: ansible_facts['os_family']|lower == 'debian' or ansible_facts['os_family']|lower == 'ubuntu'

- name: Setup for Archlinux
  import_tasks: pacman.yml
  when: ansible_facts['os_family']|lower == 'archlinux'

- name: ensure local user
  import_tasks: localuser.yml